### ISSUE TITLE
Method for structure design 

### ISSUE THREAD

**Issue by bl-2633** [hefeda/tmp#1]
Hey, can you include our method on end-to-end backbone design method as described in https://www.biorxiv.org/content/10.1101/2022.07.09.499440v1 ? We will have a code base released soon as well. Thanks!

**Comment by noeliaferruz** [comment]
Hey thanks for reaching out! I hadn't seen this paper, very interesting.

Reading it (a bit quickly) I think it would fit in class 2: structure generation, in this case, conditioned by a starting topology that you can for example build with TopoBuilder (whose preprint also I hadn't seen: https://www.biorxiv.org/content/10.1101/2022.04.07.487481v1.full)

What method do you use for inverse folding (getting the sequence libraries)?

Do you have a notion of the number of parameters?
Thanks!

**Comment by bl-2633** [comment]
Thank you for getting back. For the inverse folding module, we used our in-house SE(3) fixed backbone design described in https://www.biorxiv.org/content/10.1101/2022.04.15.488492v1.abstract

The number of parameters for our models described in the pre-print is around 1-2M. 

We will soon release a version of our model that can do coarse-grained backbone generation(This is more like the TopoBuilder but much more flexible and efficient) 

Thanks!
